spring.application.name=interviews
server.port=8080
spring.devtools.restart.enabled=false


# Hibernate second-level and query cache
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.javax.persistence.sharedCache.mode=ENABLE_SELECTIVE
spring.jpa.properties.javax.cache.uri=classpath:ehcache.xml


# Spring cache JCache provider configuration
spring.cache.type=jcache
spring.cache.jcache.config=classpath:ehcache.xml
